version: '3'

services:
  php:
    build:
      context: /home/rumi/Desktop/projet/models/config/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /home/rumi/Desktop/projet:/var/www/html
    


  db: 
    image: mysql:latest
    container_name: mysql-php
    ports:
    - "3306:3306"
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root 
  
  
      


